// PICTURES
export const SET_PICTURES = "PICTURES/SET_PICTURES";
export const SET_MORE_PICTURES = "PICTURES/SET_MORE_PICTURES";
export const SET_ACTIVE_PICTURE_ID = "PICTURES/SET_ACTIVE_PICTURE_ID";
export const SET_ACTIVE_PAGE = "PICTURES/SET_ACTIVE_PAGE";
export const ADD_COMMENT_TO_PICTURE = "PICTURES/ADD_COMMENT_TO_PICTURE";
export const INCREMENT_ACTIVE_PAGE = "PICTURES/INCREMENT_ACTIVE_PAGE";
export const DECREMENT_ACTIVE_PAGE = "PICTURES/DECREMENT_ACTIVE_PAGE";
export const INCREMENT_COMMENTS_COUNT = "PICTURES/INCREMENT_COMMENTS_COUNT";
export const DECREMENT_COMMENTS_COUNT = "PICTURES/DECREMENT_COMMENTS_COUNT";

// UI
export const ANIMATE_TO_PICTURES = "UI/ANIMATE_TO_PICTURES";
